files:
  - source: /client/src/i18n/locales/en/translation.po
    translation: /client/src/i18n/locales/%two_letters_code%/translation.po
  - source: /server/src/i18n/locales/en/translation.po
    translation: /server/src/i18n/locales/%two_letters_code%/translation.po
