preserve_hierarchy: false
files:
  - source: /client/src/i18n/locale/en/translation.json
    translation: /client/src/i18n/locale/%locale%/translation.json
  - source: /server/src/i18n/locale/en/translation.json
    translation: /server/src/i18n/locale/%locale%/translation.json
