version: '3'

services:
  mediatracker:
    container_name: mediatracker
    build: ..
    volumes:
      - ~/assets:/assets
      - ~/storage:/storage
      - ~/logs:/logs
    environment:
      - DEMO=1
  proxy:
    container_name: proxy
    hostname: proxy
    build: .
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mediatracker
    volumes:
      - /etc/letsencrypt/live/mediatracker.app/fullchain.pem:/etc/ssl/private/fullchain.pem:ro
      - /etc/letsencrypt/live/mediatracker.app/privkey.pem:/etc/ssl/private/privkey.pem:ro
    environment:
      - ADDRESS=mediatracker.app
