name: Codecov

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Codecov
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 17
      - run: npm install
      - run: npm run test:coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: server/coverage/clover.xml
          verbose: true
