name: 'coverage'

on: [pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npm run test:coverage
          coverage-file: server/coverage/coverage-final.json
