name: Update demo website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: 
      group: update_demo_website
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir .ssh
          echo "${{ secrets.VPS_PRIVATE_KEY }}" > key
          chmod 700 key
          ssh -o "StrictHostKeyChecking no" -i key ${{ secrets.VPS_LOGIN }} "
            git clone https://github.com/bonukai/MediaTracker.git 
            docker-compose --file MediaTracker/docker-reverse-proxy/docker-compose.yaml up --build --force-recreate --detach
            rm -rf MediaTracker
            docker system prune -a
          "
          rm key
