name: Tests

on: [push, pull_request]

jobs:
  build:
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 17
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      
  test:
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        node: ['16', '17']
        os: [ubuntu-20.04, ubuntu-18.04, windows-latest]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run test
